### ISSUE TITLE
ReceiptValidationError error 3

### ISSUE THREAD

**Issue by lunento** [andrewcbancroft/SwiftyLocalReceiptValidator#3]
After your great tutorial and a few modifications I am now getting:

**ReceiptValidationError error 3**

Yet, when I use the "fetchReceipt()" you also provided, it shows that YES THE RECEIPT is found.

Please help.

**Comment by TheRebelMan** [comment]
This error corresponds to "case appleRootCertificateNotFound"
You need to download the Apple Root Certificate:
[https://www.apple.com/certificateauthority/](url)
Its the first one of the top left side. Drag and drop it into your target project, and make sure to tick "Target Membership >> Yourproject"

**Comment by andrewcbancroft** [comment]
@lunento -- Did @TheRebelMan's solution work for you?
