### ISSUE TITLE
Weird Bug

### ISSUE THREAD

**Issue by i-arun-samui** [andrewcbancroft/SwiftyLocalReceiptValidator#7]
Hi,

First first for sharing your library.

When I add your code to my app the debug var window stop providing values for any variable in the app. If I remove #import <openssl/x509.h> from bridging header it start working again. 

Any idea of what can cause this?  I'm surprise because I did implement your code in another app and everything works fine ... 

Thanks ;-)

**Comment by sigmundfridge** [comment]
I assume I'm seeing the same thing (using the demo here)..... If I try to po anything in lldb I get the following
```
warning: Swift error in module SwiftyLocalReceiptValidatorDemo.
Debug info from this module will be unavailable in the debugger.

error: in auto-import:
failed to get module 'SwiftyLocalReceiptValidatorDemo' from AST context:
/Users/me/Downloads/SwiftyLocalReceiptValidator-master/Demo/SwiftyLocalReceiptValidatorDemo/SwiftyLocalReceiptValidatorDemo-Bridging-Header.h:8:9: note: in file included from /Users/me/Downloads/SwiftyLocalReceiptValidator-master/Demo/SwiftyLocalReceiptValidatorDemo/SwiftyLocalReceiptValidatorDemo-Bridging-Header.h:8:
#import <openssl/x509.h>
        ^

/Users/me/Downloads/SwiftyLocalReceiptValidator-master/Demo/Pods/Headers/Public/OpenSSL/openssl/x509.h:96:13: note: in file included from /Users/me/Downloads/SwiftyLocalReceiptValidator-master/Demo/Pods/Headers/Public/OpenSSL/openssl/x509.h:96:
#   include <openssl/rsa.h>
            ^

error: /Users/me/Downloads/SwiftyLocalReceiptValidator-master/Demo/Pods/Headers/Public/OpenSSL/openssl/rsa.h:96:51: error: expected ')'
    int (*rsa_mod_exp) (BIGNUM *r0, const BIGNUM *I, RSA *rsa, BN_CTX *ctx);
                                                  ^

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk/usr/include/complex.h:42:11: note: expanded from macro 'I'
#define I _Complex_I
          ^

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk/usr/include/complex.h:40:21: note: expanded from macro '_Complex_I'
#define _Complex_I (__extension__ 1.0iF)
                    ^

/Users/me/Downloads/SwiftyLocalReceiptValidator-master/Demo/Pods/Headers/Public/OpenSSL/openssl/rsa.h:96:51: note: to match this '('
    int (*rsa_mod_exp) (BIGNUM *r0, const BIGNUM *I, RSA *rsa, BN_CTX *ctx);
                                                  ^

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk/usr/include/complex.h:42:11: note: expanded from macro 'I'
#define I _Complex_I
          ^

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk/usr/include/complex.h:40:20: note: expanded from macro '_Complex_I'
#define _Complex_I (__extension__ 1.0iF)
                   ^

error: failed to import bridging header '/Users/me/Downloads/SwiftyLocalReceiptValidator-master/Demo/SwiftyLocalReceiptValidatorDemo/SwiftyLocalReceiptValidatorDemo-Bridging-Header.h'

```

**Comment by sigmundfridge** [comment]
Looks like an openssl issue.....
https://github.com/FredericJacobs/OpenSSL-Pod/issues/45

**Comment by andrewcbancroft** [comment]
So is this just an issue with the debugger, or are you completely unable to load, parse, and validate receipts?

Thank you @sigmundfridge, for responding to @i-arun-samui's question. Hope you're both doing well!

**Comment by sigmundfridge** [comment]
It's just the debugger. There is a fix on the link I included but it hasn't been merged back into the project. Using a different openssl library would solve the issue.

On 14 Jul 2018 20:08, Andrew Bancroft <notifications@github.com> wrote:

So is this just an issue with the debugger, or are you completely unable to load, parse, and validate receipts?

Thank you @sigmundfridge<https://github.com/sigmundfridge>, for responding to @i-arun-samui<https://github.com/i-arun-samui>'s question. Hope you're both doing well!

**Comment by andrewcbancroft** [comment]
Ok, excellent.  

I think that since it's an issue with that particular OpenSSL library, I'm going to close this issue.  

I really appreciate the contribution you made to helping track down what was going on here, @sigmundfridge!

**Comment by i-arun-samui** [comment]
Thank for finding the cause.

I do use the pod  'OpenSSL-Universal' and everything (debugger) is back to normal

Thanks
