### ISSUE TITLE
Use of unresolved identifier c2i_ASN1_INTEGER 

### ISSUE THREAD

**Issue by simonmitchell** [andrewcbancroft/SwiftyLocalReceiptValidator#8]
I'm trying to use code similar to this, however with the version of OpenSSL (v1.1.1) that I have compiled myself (Using a similar script to the CocoaPod you use) I get `Use of unresolved identifier c2i_ASN1_INTEGER`. It seems like that file is in the `Crypto` framework rather than the `OpenSSL` framework, but even if I get that into an importable state it doesn't work 😞

I'm very new to cryptography and trying to use OpenSSL, do you have any ideas?

**Comment by simonmitchell** [comment]
Hi there! Thanks for the quick response 😊 I ended up doing what you did with `pkcs7_union_accessors.h` and copy-pasting the code from the `c` file in the `Crypto` library into my project and all works nicely! Will mark this as closed 😄

**Comment by andrewcbancroft** [comment]
Oh awesome!  I'm glad that union accessor workaround worked.  I couldn't tell if that could be the source of the problem or not, haha.  Thanks for following up and closing out the issue with your solution. Hope you have a great day, Simon!

**Comment by chamitha** [comment]
I am having this issue as well. Is there a solution without the need to copy across C code?

**Comment by simonmitchell** [comment]
Hi @chamitha, I tried to go the route of also importing the headers from where this code has moved to, but couldn’t get that to work! I haven’t been on this project for a while, but will try and get a code example to you soon!

**Comment by zzdravkin** [comment]
Problem is your  Header Search Paths and  Library Search Paths

If you add folder OpenSSL to your project, and all files for OpenSSL will be there.
Add OpenSSL folder to the top of your Project (not in subfolders)

Click on the project
Select the application’s target
Select the Build Settings tab
Select the All and Combined filters.
Add the following values:

$(PROJECT_DIR)/OpenSSL/include    -   Header Search Paths
$(PROJECT_DIR)/OpenSSL/lib        -   Library Search Paths

**Comment by aalenliang** [comment]
https://github.com/openssl/openssl/issues/7538

The c2i functions are considered internal only and were removed from the public API in OpenSSL 1.1.0. You should use the d2i equivalents instead.

Maybe we should use `d2i_ASN1_INTEGER` instead of `c2i_ASN1_INTEGER`? But apparently, they are not the same, it's really difficult for me to convert the c2i function call into the d2i version.

**Comment by thejeff77** [comment]
This was my solution based off of openssl#7538

```
    func DecodeASN1Integer(startOfInt intPointer: inout UnsafePointer<UInt8>?, length: Int) -> Int? {
        let integer = d2i_ASN1_UINTEGER(nil, &intPointer, length)
        let result = ASN1_INTEGER_get(integer)
        ASN1_INTEGER_free(integer)
        return result
    }
```

**Comment by Rumy-hasan** [comment]
[here](https://stackoverflow.com/questions/56388735/c2i-asn1-integer-function-in-openssl-1-1-0) is an explanation for understanding how it works.
